title: Krishanu Kumar # your name (or website title) here
logo: "/IMG_3531.jpg" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Researcher at TAU
  <br><br>
  Experimental fluid mechanics | Multiphase flow | Droplet dynamics in wave breaking | Wind Waves
  <br><br>
  <a href="./">Research</a>
  <br>
  <a href="./about_me">About Me</a>
  <br><br>
  <a href="https://scholar.google.com/citations?user=l9c73IQAAAAJ&hl=en">Google Scholar</a> | <a href="https://www.linkedin.com/in/krishanu-kumar-973814105/">LinkedIn</a> | <a href="https://www.researchgate.net/profile/Krishanu-Kumar?ev=hdr_xprf">RG</a> | <a href="./Resume_krishanu_kumar_2025.pdf" target="_blank" rel="noopener noreferrer">CV</a>
  
theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here
#github:
#  is_project_page: false
